Decentraland/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData
import config


naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()


app = Flask(__name__)
app.config.from_object(config)
app.debug = True

# DRM 데이터베이스 초기화
db.init_app(app)

migrate.init_app(app,db)

from .views import main_views,Chatbot_views,price_trend,homepage,marketplace,Chathook_views
app.register_blueprint(main_views.bp)
app.register_blueprint(Chatbot_views.bp)
app.register_blueprint(price_trend.bp)
app.register_blueprint(homepage.bp)
app.register_blueprint(marketplace.bp)
app.register_blueprint(Chathook_views.bp)

Decentraland/views/Chatbot_views.py
from flask import Blueprint , render_template,url_for,request,flash,session,g

from werkzeug.utils import redirect

bp= Blueprint('chatbot',__name__,url_prefix='/')

@bp.route('/chatbot',methods=('GET',))
def chatbot():
    return render_template('chatbot/chatbot.html')

Decentraland/views/Chathook_views.py
from flask import Blueprint,request
from Decentraland.APIs import Dailyparcel
from Decentraland.APIs import Dailymanawon
from Decentraland.APIs import Historydetail
import json




bp= Blueprint('chathook',__name__,url_prefix='/')

@bp.route('/chathook',methods=['GET','POST'])
def chat():
    req= request.get_json(force=True)
    if req['queryResult']['intent']['displayName'] == 'CurrentPrice':
        result=Dailyparcel()
        result2=Dailymanawon()
        result=result['price']
        result3=result*result2
        senddata = '오늘의 1파셀의 평균가격은' + str(result) + ' MANA입니다.' + '1MANA의 가격은' + str(result2) + '원입니다.' + ' 1파셀의 평균가격을 원화로 환산하면' + \
                   str(result3) + ' 원입니다.'

    elif req['queryResult']['intent']['displayName'] == 'Date':
        date = req['queryResult']['queryText']
        result=Historydetail(date)
        senddata = date+ '의 1파셀의 평균가격은' + str(result['price']) + ' MANA입니다.' + ' 1MANA의 가격은' + str(result['mana per won'])+ '원입니다.' + ' 1파셀의 평균가격을 원화로 환산하면' + \
                   str(result['won price']) + ' 원입니다.'

    return {'fulfillmentText': senddata}

Decentraland/views/homepage.py
from flask import Blueprint , render_template,url_for
from Decentraland import db
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('homepage', __name__, url_prefix='/')

@bp.route('/homepage')
def home():
    return redirect("https://decentraland.org/")

Decentraland/views/main_views.py
from flask import Blueprint , render_template,url_for
from Decentraland import db
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return render_template('main.html')

Decentraland/views/marketplace.py
from flask import Blueprint , render_template,url_for
from Decentraland import db
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('marketplace', __name__, url_prefix='/')

@bp.route('/marketplace')
def market():
    return redirect("https://market.decentraland.org/")

Decentraland/views/price_trend.py
from flask import Blueprint , render_template,url_for
from Decentraland import db
from datetime import datetime
from werkzeug.utils import redirect

bp = Blueprint('pricetrend', __name__, url_prefix='/')

@bp.route('/pricetrend')
def trend():
    return render_template('trend.html')

Decentraland/templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Decentraland 정보 페이지입니다.</title>
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="canonical" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='jumbotron.css') }}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" style="font-family: 'Lobster';" href="{{url_for('main.index')}}">Decentraland</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.index')}}">Home </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">메뉴</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{{url_for('chatbot.chatbot')}}">챗봇</a>
          <a class="dropdown-item" href="{{url_for('pricetrend.trend')}}">가격 동향</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}

Decentraland/templates/chatbot/chatbot.html
{% extends 'base.html' %}
{% block content %}
<main role="main" class="col-md-1 ml-sm-auto col-lg-12 px-md-3">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Ask Price!</h1>



      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
     <iframe
    style= "position: absolute;
    left:14%;
    top:40%;
    margin-left: -150px;
    margin-top: -170px;"
    allow="microphone;"
    width="500"
    height="500"
    src="https://console.dialogflow.com/api-client/demo/embedded/308022f7-1048-4fc7-8fc5-e671a0fede8b">
</iframe>




<iframe style= "position: absolute;
    right:16%;
    top:40%;
    margin-right: -150px;
    margin-top: -170px;" src="https://kr.widgets.investing.com/top-cryptocurrencies?theme=darkTheme" width="50%" height="100%" frameborder="0" allowtransparency="true" marginwidth="0" marginheight="0"></iframe><div class="poweredBy" style="font-family: Arial, Helvetica, sans-serif;"><a href="https://kr.investing.com?utm_source=WMT&amp;utm_medium=referral&amp;utm_campaign=TOP_CRYPTOCURRENCIES&amp;utm_content=Footer%20Link" target="_blank" rel="nofollow"></a></div>
</main>
{% endblock %}

Decentraland/templates/main.html
{% extends 'base.html' %}
{% block content %}


<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3" style="font-family: 'Lobster';">Decentraland</h1>
      <p>디센트럴랜드는 이더리움 블록체인을 기반으로 하는 가상현실 플랫폼입니다. 디센트럴 랜드의 토지는 이더리움 스마트 계약에 저장되어 있으며 대체가 불가능하고 양도할 수 있는 유한한 디지털 자산입니다. 지금 디센트럴랜드의 토지가격을 알아보세요!</p>
      <p><a class="btn btn-info btn-lg" href="{{url_for('chatbot.chatbot')}}" role="button">챗봇으로 더 알아보기&raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>가격동향</h2>
        <p>디센트럴랜드의 토지의 가격은 꾸준히 상승하고 있습니다. 화폐가치가 떨어지고 있는 지금, 디센트럴랜드의 토지를 구매하여 인플레이션에 대처하세요!</p>
        <p><a class="btn btn-secondary" href="{{url_for('pricetrend.trend')}}" role="button">가격동향으로 이동 &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>홈페이지</h2>
        <p>디센트럴랜드안에서 메타마스크 지갑을 만들고 다양한 증강현실과 NFT예술작품, 카지노와 드래곤탑승등 여러가지 컨텐츠를 즐겨보세요! 토지 구입은 옵션입니다!</p>
        <p><a class="btn btn-secondary" href={{url_for('homepage.home')}} role="button">홈페이지로 이동 &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>마켓 플레이스</h2>
        <p>디센트럴랜드 마켓에서 디센트럴랜드의 토지뿐만아니라 캐릭터를 위한 코스튬, 대량의 부동산등 다양한 물건을 구입해보세요! 구입에 통용되는 화폐는 MANA입니다.</p>
        <p><a class="btn btn-secondary" href={{url_for('marketplace.market')}} role="button">마켓으로 이동 &raquo;</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; Seokclarinet 2021</p>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
</html>

{% endblock %}

Decentraland/templates/trend.html
{% extends 'base.html' %}
{% block content %}
<body>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <table border="0">
	<th>
      <div class="col-md-9 px-0">
      <h2 class="display-4 font-italic">디센트럴랜드의 부동산은 계속해서 성장하고 있습니다.</h2>
      <p class="lead my-3">현실의 부동산과 달리 디센트럴랜드의 가상부동산은 변동하는 MANA가격을 반영하여 변동성이 높습니다.</p>
    </div>
      </th>
      <th>
 <!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_14fae"></div>
  <div class="tradingview-widget-copyright">TradingView 제공 <a href="https://kr.tradingview.com/symbols/MANAKRW/?exchange=BITHUMB" rel="noopener" target="_blank"><span class="blue-text">MANAKRW 차트</span></a></div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "width": 780,
  "height": 510,
  "symbol": "BITHUMB:MANAKRW",
  "interval": "D",
  "timezone": "Etc/UTC",
  "theme": "light",
  "style": "1",
  "locale": "kr",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "tradingview_14fae"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->
      </th>




    </table>
    </div>




  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-danger">1MANA의 원화가격 그래프</strong>
        <img src="{{ url_for('static', filename='mana_won.png') }}">


        </div>

      </div>
    </div>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-success">1Parcel의 원화가격 그래프</strong>
        <img src="{{ url_for('static', filename='pacel_won.png') }}">
        </div>

      </div>
    </div>
  </div>
</div>


</body>
</html>




{% endblock %}